version: '3.9'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: BudgetWiseAPI
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:root1234@mysql-db:3306/BudgetWiseAPI
      SECRET_KEY: Paris1234
      USE_ENV_FILE: false
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/requirements.txt
      
volumes:
  mysql_data:
